Created branch to add Work section for Portfolio
HAMMAS-SALEEM/Portfolio pull request #3
Opened 2021-11-26 22:22 UTC by HAMMAS-SALEEM

This is my first Project in Microverse Program but this is my second branch on the same repository.

Things added:

Work Section in Markup (HTML)
Style Work Section (CSS)
Some Debugging of HTML & CSS

2021-11-26 23:18 UTC, ignatius22 requested changes
## Hi @HAMMAS-SALEEM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Having a descriptive class name is a very good practice that can make you more professional


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 23:18 UTC, ignatius22 commented on index.html
> +        <div class="about-me">
- [ ] Let's make sure we follow the proper guidelines by making this container a` section` tag

2021-11-26 23:18 UTC, ignatius22 commented on index.html
> +            <div class="cr-grid">
- [ ] Let's ensure we follow good practice by using more semantic tags  (`section`  tag) for this container.

2021-11-26 23:18 UTC, ignatius22 commented on index.html
> +                <h2 class="works-title">Multi-Post Stories</h2>
- [ ] I think it would be nice to use the `header` tag for our project title.

2021-11-26 23:18 UTC, ignatius22 commented on index.html
> +                <h2 class="works-title">Tonic</h2>
- [ ] I think it would be nice to use the `header` tag for our project title.

2021-11-27 07:43 UTC, HAMMAS-SALEEM commented
Thanks for reaching me out. I want to ask about the last requirement. I did
not know what project title are you talking about. Can you tell me in which
section and for which project title i need to use header tag.

On Sat, Nov 27, 2021, 4:18 AM Ignatius Sani ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @HAMMAS-SALEEM <https://github.com/HAMMAS-SALEEM>,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
>    - Having a descriptive class name is a very good practice that can
>    make you more professional
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757711741>:
>
> > +                <ul class="specs w11contain">
>
> +                    <li class="spec1">CANOPY</li>
>
> +                    <li class="spec2">Back End Dev</li>
>
> +                    <li class="spec2">2015</li>
>
> +                </ul>
>
> +                <p class="w1par">A daily selection of privately personalized reads; no accounts or sign-ups required.
>
> +                </p>
>
> +                <div class="bcontain">
>
> +                    <button class="w1btn" disabled>html</button>
>
> +                    <button class="w1btn w1b" disabled>css</button>
>
> +                    <button class="w1btn w1b" disabled>javaScript</button>
>
> +                </div>
>
> +                <button class="w1btn2">See Project</button>
>
> +            </div>
>
> +        </div>
>
> +        <div class="about-me">
>
>
>
>    - Let's make sure we follow the proper guidelines by making this
>    container a section tag
>
> ------------------------------
>
> In index.html
> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757714690>:
>
> > +                <p class="description">I’m a software developer! I can help you build a product , feature or website
>
> +                    Look through some of my work and experience! If you like what you see and have a project you need
>
> +                    coded,
>
> +                    don’t hestiate to contact me. </p>
>
> +                <div class="container2">
>
> +                    <p class="connect">LET'S CONNECT</p>
>
> +                    <ul class="icon-list">
>
> +                        <li><a href="#" class="fa fa-twitter fa-color" aria-hidden="true"></a></li>
>
> +                        <li><a href="#" class="fa fa-linkedin fa-color" aria-hidden="true"></a></li>
>
> +                        <li><a href="#" class="fa fa-medium fa-color" aria-hidden="true"></a></li>
>
> +                        <li><a href="#" class="fa fa-github fa-color" aria-hidden="true"></a></li>
>
> +                        <li> <a href="#" class="fa fa-angellist fa-color" aria-hidden="true"></a></li>
>
> +                    </ul>
>
> +                </div>
>
> +            </div>
>
> +            <div class="cr-grid">
>
>
>
>    - Let's ensure we follow good practice by using more semantic tags (
>    section tag) for this container.
>
> ------------------------------
>
> In index.html
> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757715120>:
>
> > +                    <li class="spec1">CANOPY</li>
>
> +                    <li class="spec2">Back End Dev</li>
>
> +                    <li class="spec2">2015</li>
>
> +                </ul>
>
> +                <p class="w1par">A daily selection of privately personalized reads; no accounts or sign-ups required.
>
> +                </p>
>
> +                <div class="bcontain">
>
> +                    <button class="w1btn" disabled>html</button>
>
> +                    <button class="w1btn w1b" disabled>css</button>
>
> +                    <button class="w1btn w1b" disabled>javaScript</button>
>
> +                </div>
>
> +                <button class="w1btn2">See Project</button>
>
> +            </div>
>
> +            <div class="w1contain">
>
> +                <img class="pti" src="./images/SP2.png" alt="Portfolio Title Image">
>
> +                <h2 class="works-title">Multi-Post Stories</h2>
>
>
>
>    - I think it would be nice to use the header tag for our project title.
>
> ------------------------------
>
> In index.html
> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757715188>:
>
> > +                    don’t hestiate to contact me. </p>
>
> +                <div class="container2">
>
> +                    <p class="connect">LET'S CONNECT</p>
>
> +                    <ul class="icon-list">
>
> +                        <li><a href="#" class="fa fa-twitter fa-color" aria-hidden="true"></a></li>
>
> +                        <li><a href="#" class="fa fa-linkedin fa-color" aria-hidden="true"></a></li>
>
> +                        <li><a href="#" class="fa fa-medium fa-color" aria-hidden="true"></a></li>
>
> +                        <li><a href="#" class="fa fa-github fa-color" aria-hidden="true"></a></li>
>
> +                        <li> <a href="#" class="fa fa-angellist fa-color" aria-hidden="true"></a></li>
>
> +                    </ul>
>
> +                </div>
>
> +            </div>
>
> +            <div class="cr-grid">
>
> +            <div class="w1contain">
>
> +                <img class="pti" src="./images/SP.png" alt="Portfolio Title Image">
>
> +                <h2 class="works-title">Tonic</h2>
>
>
>
>    - I think it would be nice to use the header tag for our project title.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#pullrequestreview-817080586>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWF2V72I5N4P5BGJ3QRO6KTUOAIUBANCNFSM5I3N2WVA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-27 08:24 UTC, HAMMAS-SALEEM commented
One more thing I want to talk about is should I use one section tag for
about-me because ul and li are inside this tag so why should I use another
section for li such as Languages, Frameworks, skills.

On Sat, Nov 27, 2021 at 12:43 PM Hammas Saleem ***@***.***>
wrote:

> Thanks for reaching me out. I want to ask about the last requirement. I
> did not know what project title are you talking about. Can you tell me in
> which section and for which project title i need to use header tag.
>
> On Sat, Nov 27, 2021, 4:18 AM Ignatius Sani ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>> Hi @HAMMAS-SALEEM <https://github.com/HAMMAS-SALEEM>,
>>
>> Good job so far!
>> There are some issues that you still need to work on to go to the next
>> project but you are almost there!
>> Required Changes ♻️
>>
>> *Check the comments under the review.*
>> Optional suggestions
>>
>> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
>> the approval of this PR. However, I strongly recommend you to take them
>> into account as they can make your code better.*
>>
>> You can also consider:
>>
>>    - Having a descriptive class name is a very good practice that can
>>    make you more professional
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *As described in the Code reviews limits policy
>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>> limited number of reviews per project (check the exact number in your
>> Dashboard). If you think that the code review was not fair, you can request
>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>> ------------------------------
>>
>> In index.html
>> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757711741>
>> :
>>
>> > +                <ul class="specs w11contain">
>>
>> +                    <li class="spec1">CANOPY</li>
>>
>> +                    <li class="spec2">Back End Dev</li>
>>
>> +                    <li class="spec2">2015</li>
>>
>> +                </ul>
>>
>> +                <p class="w1par">A daily selection of privately personalized reads; no accounts or sign-ups required.
>>
>> +                </p>
>>
>> +                <div class="bcontain">
>>
>> +                    <button class="w1btn" disabled>html</button>
>>
>> +                    <button class="w1btn w1b" disabled>css</button>
>>
>> +                    <button class="w1btn w1b" disabled>javaScript</button>
>>
>> +                </div>
>>
>> +                <button class="w1btn2">See Project</button>
>>
>> +            </div>
>>
>> +        </div>
>>
>> +        <div class="about-me">
>>
>>
>>
>>    - Let's make sure we follow the proper guidelines by making this
>>    container a section tag
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757714690>
>> :
>>
>> > +                <p class="description">I’m a software developer! I can help you build a product , feature or website
>>
>> +                    Look through some of my work and experience! If you like what you see and have a project you need
>>
>> +                    coded,
>>
>> +                    don’t hestiate to contact me. </p>
>>
>> +                <div class="container2">
>>
>> +                    <p class="connect">LET'S CONNECT</p>
>>
>> +                    <ul class="icon-list">
>>
>> +                        <li><a href="#" class="fa fa-twitter fa-color" aria-hidden="true"></a></li>
>>
>> +                        <li><a href="#" class="fa fa-linkedin fa-color" aria-hidden="true"></a></li>
>>
>> +                        <li><a href="#" class="fa fa-medium fa-color" aria-hidden="true"></a></li>
>>
>> +                        <li><a href="#" class="fa fa-github fa-color" aria-hidden="true"></a></li>
>>
>> +                        <li> <a href="#" class="fa fa-angellist fa-color" aria-hidden="true"></a></li>
>>
>> +                    </ul>
>>
>> +                </div>
>>
>> +            </div>
>>
>> +            <div class="cr-grid">
>>
>>
>>
>>    - Let's ensure we follow good practice by using more semantic tags (
>>    section tag) for this container.
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757715120>
>> :
>>
>> > +                    <li class="spec1">CANOPY</li>
>>
>> +                    <li class="spec2">Back End Dev</li>
>>
>> +                    <li class="spec2">2015</li>
>>
>> +                </ul>
>>
>> +                <p class="w1par">A daily selection of privately personalized reads; no accounts or sign-ups required.
>>
>> +                </p>
>>
>> +                <div class="bcontain">
>>
>> +                    <button class="w1btn" disabled>html</button>
>>
>> +                    <button class="w1btn w1b" disabled>css</button>
>>
>> +                    <button class="w1btn w1b" disabled>javaScript</button>
>>
>> +                </div>
>>
>> +                <button class="w1btn2">See Project</button>
>>
>> +            </div>
>>
>> +            <div class="w1contain">
>>
>> +                <img class="pti" src="./images/SP2.png" alt="Portfolio Title Image">
>>
>> +                <h2 class="works-title">Multi-Post Stories</h2>
>>
>>
>>
>>    - I think it would be nice to use the header tag for our project
>>    title.
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757715188>
>> :
>>
>> > +                    don’t hestiate to contact me. </p>
>>
>> +                <div class="container2">
>>
>> +                    <p class="connect">LET'S CONNECT</p>
>>
>> +                    <ul class="icon-list">
>>
>> +                        <li><a href="#" class="fa fa-twitter fa-color" aria-hidden="true"></a></li>
>>
>> +                        <li><a href="#" class="fa fa-linkedin fa-color" aria-hidden="true"></a></li>
>>
>> +                        <li><a href="#" class="fa fa-medium fa-color" aria-hidden="true"></a></li>
>>
>> +                        <li><a href="#" class="fa fa-github fa-color" aria-hidden="true"></a></li>
>>
>> +                        <li> <a href="#" class="fa fa-angellist fa-color" aria-hidden="true"></a></li>
>>
>> +                    </ul>
>>
>> +                </div>
>>
>> +            </div>
>>
>> +            <div class="cr-grid">
>>
>> +            <div class="w1contain">
>>
>> +                <img class="pti" src="./images/SP.png" alt="Portfolio Title Image">
>>
>> +                <h2 class="works-title">Tonic</h2>
>>
>>
>>
>>    - I think it would be nice to use the header tag for our project
>>    title.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#pullrequestreview-817080586>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AWF2V72I5N4P5BGJ3QRO6KTUOAIUBANCNFSM5I3N2WVA>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-11-27 08:34 UTC, HAMMAS-SALEEM commented
I wanted to ask about work section not about-me section
Sorry for my mistake.


On Sat, Nov 27, 2021 at 1:24 PM Hammas Saleem ***@***.***>
wrote:

> One more thing I want to talk about is should I use one section tag for
> about-me because ul and li are inside this tag so why should I use another
> section for li such as Languages, Frameworks, skills.
>
> On Sat, Nov 27, 2021 at 12:43 PM Hammas Saleem ***@***.***>
> wrote:
>
>> Thanks for reaching me out. I want to ask about the last requirement. I
>> did not know what project title are you talking about. Can you tell me in
>> which section and for which project title i need to use header tag.
>>
>> On Sat, Nov 27, 2021, 4:18 AM Ignatius Sani ***@***.***>
>> wrote:
>>
>>> ***@***.**** requested changes on this pull request.
>>> Hi @HAMMAS-SALEEM <https://github.com/HAMMAS-SALEEM>,
>>>
>>> Good job so far!
>>> There are some issues that you still need to work on to go to the next
>>> project but you are almost there!
>>> Required Changes ♻️
>>>
>>> *Check the comments under the review.*
>>> Optional suggestions
>>>
>>> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
>>> the approval of this PR. However, I strongly recommend you to take them
>>> into account as they can make your code better.*
>>>
>>> You can also consider:
>>>
>>>    - Having a descriptive class name is a very good practice that can
>>>    make you more professional
>>>
>>> Cheers and Happy coding!👏👏👏
>>>
>>> Feel free to leave any questions or comments in the PR thread if
>>> something is not 100% clear.
>>>
>>> *Please, do not open a new Pull Request for re-reviews. You should use
>>> the same Pull Request submitted for the first review, either valid or
>>> invalid unless it is requested otherwise.*
>>> ------------------------------
>>>
>>> *As described in the Code reviews limits policy
>>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>>> limited number of reviews per project (check the exact number in your
>>> Dashboard). If you think that the code review was not fair, you can request
>>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757711741>
>>> :
>>>
>>> > +                <ul class="specs w11contain">
>>>
>>> +                    <li class="spec1">CANOPY</li>
>>>
>>> +                    <li class="spec2">Back End Dev</li>
>>>
>>> +                    <li class="spec2">2015</li>
>>>
>>> +                </ul>
>>>
>>> +                <p class="w1par">A daily selection of privately personalized reads; no accounts or sign-ups required.
>>>
>>> +                </p>
>>>
>>> +                <div class="bcontain">
>>>
>>> +                    <button class="w1btn" disabled>html</button>
>>>
>>> +                    <button class="w1btn w1b" disabled>css</button>
>>>
>>> +                    <button class="w1btn w1b" disabled>javaScript</button>
>>>
>>> +                </div>
>>>
>>> +                <button class="w1btn2">See Project</button>
>>>
>>> +            </div>
>>>
>>> +        </div>
>>>
>>> +        <div class="about-me">
>>>
>>>
>>>
>>>    - Let's make sure we follow the proper guidelines by making this
>>>    container a section tag
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757714690>
>>> :
>>>
>>> > +                <p class="description">I’m a software developer! I can help you build a product , feature or website
>>>
>>> +                    Look through some of my work and experience! If you like what you see and have a project you need
>>>
>>> +                    coded,
>>>
>>> +                    don’t hestiate to contact me. </p>
>>>
>>> +                <div class="container2">
>>>
>>> +                    <p class="connect">LET'S CONNECT</p>
>>>
>>> +                    <ul class="icon-list">
>>>
>>> +                        <li><a href="#" class="fa fa-twitter fa-color" aria-hidden="true"></a></li>
>>>
>>> +                        <li><a href="#" class="fa fa-linkedin fa-color" aria-hidden="true"></a></li>
>>>
>>> +                        <li><a href="#" class="fa fa-medium fa-color" aria-hidden="true"></a></li>
>>>
>>> +                        <li><a href="#" class="fa fa-github fa-color" aria-hidden="true"></a></li>
>>>
>>> +                        <li> <a href="#" class="fa fa-angellist fa-color" aria-hidden="true"></a></li>
>>>
>>> +                    </ul>
>>>
>>> +                </div>
>>>
>>> +            </div>
>>>
>>> +            <div class="cr-grid">
>>>
>>>
>>>
>>>    - Let's ensure we follow good practice by using more semantic tags (
>>>    section tag) for this container.
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757715120>
>>> :
>>>
>>> > +                    <li class="spec1">CANOPY</li>
>>>
>>> +                    <li class="spec2">Back End Dev</li>
>>>
>>> +                    <li class="spec2">2015</li>
>>>
>>> +                </ul>
>>>
>>> +                <p class="w1par">A daily selection of privately personalized reads; no accounts or sign-ups required.
>>>
>>> +                </p>
>>>
>>> +                <div class="bcontain">
>>>
>>> +                    <button class="w1btn" disabled>html</button>
>>>
>>> +                    <button class="w1btn w1b" disabled>css</button>
>>>
>>> +                    <button class="w1btn w1b" disabled>javaScript</button>
>>>
>>> +                </div>
>>>
>>> +                <button class="w1btn2">See Project</button>
>>>
>>> +            </div>
>>>
>>> +            <div class="w1contain">
>>>
>>> +                <img class="pti" src="./images/SP2.png" alt="Portfolio Title Image">
>>>
>>> +                <h2 class="works-title">Multi-Post Stories</h2>
>>>
>>>
>>>
>>>    - I think it would be nice to use the header tag for our project
>>>    title.
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#discussion_r757715188>
>>> :
>>>
>>> > +                    don’t hestiate to contact me. </p>
>>>
>>> +                <div class="container2">
>>>
>>> +                    <p class="connect">LET'S CONNECT</p>
>>>
>>> +                    <ul class="icon-list">
>>>
>>> +                        <li><a href="#" class="fa fa-twitter fa-color" aria-hidden="true"></a></li>
>>>
>>> +                        <li><a href="#" class="fa fa-linkedin fa-color" aria-hidden="true"></a></li>
>>>
>>> +                        <li><a href="#" class="fa fa-medium fa-color" aria-hidden="true"></a></li>
>>>
>>> +                        <li><a href="#" class="fa fa-github fa-color" aria-hidden="true"></a></li>
>>>
>>> +                        <li> <a href="#" class="fa fa-angellist fa-color" aria-hidden="true"></a></li>
>>>
>>> +                    </ul>
>>>
>>> +                </div>
>>>
>>> +            </div>
>>>
>>> +            <div class="cr-grid">
>>>
>>> +            <div class="w1contain">
>>>
>>> +                <img class="pti" src="./images/SP.png" alt="Portfolio Title Image">
>>>
>>> +                <h2 class="works-title">Tonic</h2>
>>>
>>>
>>>
>>>    - I think it would be nice to use the header tag for our project
>>>    title.
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/HAMMAS-SALEEM/Portfolio/pull/3#pullrequestreview-817080586>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AWF2V72I5N4P5BGJ3QRO6KTUOAIUBANCNFSM5I3N2WVA>
>>> .
>>> Triage notifications on the go with GitHub Mobile for iOS
>>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>>> or Android
>>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_camp [...]

2021-11-27 09:37 UTC, Cathella approved these changes
## STATUS: APPROVED 🟢

### Hi @HAMMAS-SALEEM 👋🏻, 

You have done a tremedous job working on the changes requested by the previous reviewer 💪🏻. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-27 10:10 UTC, merged